import type { Creature } from '../types'

export const CREATURES: Creature[] = [
  // Common
  {
    id: 'flamepup',
    name: "LONTE'",
    type: 'fire',
    rarity: 'common',
    emoji: '🔥',
    baseCatchRate: 0.70,
    baseCP: 120,
    description: 'A playful pup made of living flame.',
    color: '#FF6B35',
  },
  {
    id: 'aquafin',
    name: "LONTE'",
    type: 'water',
    rarity: 'common',
    emoji: '🐟',
    baseCatchRate: 0.70,
    baseCP: 110,
    description: 'A swift fish that leaps between puddles.',
    color: '#4ECDC4',
  },
  {
    id: 'leafling',
    name: "LONTE'",
    type: 'grass',
    rarity: 'common',
    emoji: '🌿',
    baseCatchRate: 0.70,
    baseCP: 100,
    description: 'A tiny creature woven from fresh leaves.',
    color: '#7BC950',
  },
  {
    id: 'sparkbug',
    name: "LONTE'",
    type: 'electric',
    rarity: 'common',
    emoji: '✨',
    baseCatchRate: 0.70,
    baseCP: 90,
    description: 'A glowing insect that crackles with static.',
    color: '#FFE66D',
  },
  {
    id: 'dustpuff',
    name: "LONTE'",
    type: 'normal',
    rarity: 'common',
    emoji: '💨',
    baseCatchRate: 0.75,
    baseCP: 80,
    description: 'A fluffy ball of dust that drifts in the wind.',
    color: '#C9B1FF',
  },

  // Uncommon
  {
    id: 'voltkit',
    name: "LONTE'",
    type: 'electric',
    rarity: 'uncommon',
    emoji: '⚡',
    baseCatchRate: 0.50,
    baseCP: 220,
    description: 'A fox-like creature that channels lightning.',
    color: '#F7DC6F',
  },
  {
    id: 'shadowmew',
    name: "LONTE'",
    type: 'dark',
    rarity: 'uncommon',
    emoji: '🌑',
    baseCatchRate: 0.50,
    baseCP: 250,
    description: 'A cat that phases between shadows.',
    color: '#8E44AD',
  },
  {
    id: 'coralsnap',
    name: "LONTE'",
    type: 'water',
    rarity: 'uncommon',
    emoji: '🐚',
    baseCatchRate: 0.50,
    baseCP: 200,
    description: 'A snapping creature built from coral.',
    color: '#F1948A',
  },
  {
    id: 'emberfox',
    name: "LONTE'",
    type: 'fire',
    rarity: 'uncommon',
    emoji: '🦊',
    baseCatchRate: 0.45,
    baseCP: 260,
    description: 'A cunning fox wreathed in embers.',
    color: '#E74C3C',
  },

  // Rare
  {
    id: 'blazewolf',
    name: "LONTE'",
    type: 'fire',
    rarity: 'rare',
    emoji: '🐺',
    baseCatchRate: 0.30,
    baseCP: 450,
    description: 'A fierce wolf whose howl ignites the air.',
    color: '#FF4500',
  },
  {
    id: 'tideclaw',
    name: "LONTE'",
    type: 'water',
    rarity: 'rare',
    emoji: '🦀',
    baseCatchRate: 0.30,
    baseCP: 420,
    description: 'A massive crab that commands the tides.',
    color: '#1ABC9C',
  },
  {
    id: 'thornvine',
    name: "LONTE'",
    type: 'grass',
    rarity: 'rare',
    emoji: '🌹',
    baseCatchRate: 0.30,
    baseCP: 400,
    description: 'A rose dragon wrapped in thorny vines.',
    color: '#27AE60',
  },

  // Legendary
  {
    id: 'stormdrake',
    name: "LONTE'",
    type: 'electric',
    rarity: 'legendary',
    emoji: '🐉',
    baseCatchRate: 0.10,
    baseCP: 900,
    description: 'An ancient dragon that rides the storms.',
    color: '#3498DB',
  },
  {
    id: 'voidreaper',
    name: "LONTE'",
    type: 'dark',
    rarity: 'legendary',
    emoji: '👻',
    baseCatchRate: 0.10,
    baseCP: 950,
    description: 'A spectral entity from the void between worlds.',
    color: '#6C3483',
  },
]
